[Settings]
ID = "c6b86eea-bf53-4b36-bc4a-f256cee8a779"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "expat-nation/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "build"
  # This will be your default build command
  command = "yarn build"
